// This file is generated by npm run build:icons

export type IconName =
	| "caret-sort"
	| "check"
	| "chevron-down"
	| "chevron-left"
	| "chevron-right"
	| "chevron-up"
	| "cross-1"
	| "cross-2"
	| "eye-none"
	| "eye-open"
	| "laptop"
	| "moon"
	| "plus"
	| "sun"
	| "update";
