module.exports = {
	env: {
		node: true,
	},
	parser: '@typescript-eslint/parser',
	extends: [
		'turbo',
		'eslint:recommended',
		'plugin:@typescript-eslint/recommended',
		'prettier',
		'plugin:tailwindcss/recommended',
	],
	plugins: [
		'react',
		'react-hooks',
		'import',
		'tailwindcss',
		'@typescript-eslint',
		'unused-imports',
		'simple-import-sort',
	],
	parserOptions: {
		sourceType: 'module',
		ecmaVersion: 2020,
	},
	rules: {
		'react-hooks/rules-of-hooks': 'error',
		'react-hooks/exhaustive-deps': 'error',
		'react/jsx-filename-extension': ['error', { extensions: ['.ts', '.tsx'] }],
		'react/jsx-uses-react': 1,
		'react/jsx-uses-vars': 1,
		'@typescript-eslint/consistent-type-imports': [
			'warn',
			{
				prefer: 'type-imports',
				disallowTypeAnnotations: true,
				fixStyle: 'inline-type-imports',
			},
		],
		'import/no-duplicates': ['warn', { 'prefer-inline': true }],
		'import/consistent-type-specifier-style': ['warn', 'prefer-inline'],
		'@typescript-eslint/no-non-null-assertion': 'off',
		'no-var': 'off',
		'prefer-const': 'off',
		'@typescript-eslint/ban-ts-comment': 'off',
		'@typescript-eslint/no-var-requires': 'off',
		'@typescript-eslint/no-explicit-any': 'off',
		'no-unused-vars': 'off',
		'@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
		'tailwindcss/no-custom-classname': 'off',
		'import/order': [
			1,
			{
				alphabetize: { order: 'asc', caseInsensitive: true },
				groups: [
					'builtin',
					'external',
					'internal',
					'parent',
					'sibling',
					'index',
				],
				pathGroups: [
					{ pattern: '~/**', group: 'internal' },
					{ pattern: 'test/**', group: 'internal' },
					{ pattern: '@/icon-name', group: 'internal' },
				],
				'newlines-between': 'always',
			},
		],
		'jsx-quotes': ['warn', 'prefer-double'],
		'react/jsx-filename-extension': ['error', { extensions: ['.ts', '.tsx'] }],
		'react/jsx-uses-react': 1,
		'react/jsx-uses-vars': 1,
		'unused-imports/no-unused-imports-ts': 'error',
		'unused-imports/no-unused-vars-ts': [
			'error',
			{ vars: 'all', args: 'none', ignoreRestSiblings: true },
		],
		'@typescript-eslint/ban-types': 0,
		curly: 'warn',
		'import/newline-after-import': ['error', { count: 1 }],
		'simple-import-sort/exports': 'error',
	},
	ignorePatterns: [
		'**/.eslintrc.cjs',
		'**/*.config.js',
		'**/*.config.cjs',
		'.next',
		'dist',
		'pnpm-lock.yaml',
		'**/build',
		'**/public/build',
	],
}
